version: '3'
services:
    nginx:
         image: nginx:latest
         ports:
          - 90:80
         volumes:
          - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./www:/var/www/html
         links:
          - php
    php:
        image: php:7.2-fpm
        volumes:
                - ./www:/var/www/html
        # command: bash -c "apt-get update && apt-get install"
        ports:
          - 9000:9000
    postgres:
        image: postgres
        volumes:
          - ./postgres:/var/lib/postgresql/data
        ports:
          - 5431:5432
        environment:
          - POSTGRES_DB=test_docker
          - POSTGRES_USER=mehmetakkus
          - POSTGRES_PASSWORD=123123
    mysql:
        image: mysql
        environment:
          - MYSQL_DATABASE=test_docker
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_USER=mehmetakkus
          - MYSQL_PASSWORD=123123
        port:
          - 3305:3306
    pgadmin:
        image: fenglc/pgadmin4
        ports:
          - 5050:5050
    adminer:
        image: adminer
        ports:
          - 5051:8080
    mysql:
        image: mysql
        environment:
          - MYSQL_DATABASE=test_docker
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_USER=mehmetakkus
          - MYSQL_PASSWORD=123123
        volumes:
          - ./mysql:/var/lib/mysql
        ports:
          - 3305:3306
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
          - 5052:80
        depends_on:
          - mysql
        environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=mysql
